### ISSUE TITLE
Helm Kind action seems broken

### ISSUE THREAD

**Issue by ctron** [helm/kind-action#42] opened 2021-06-30 11:54 UTC
To me it looks like the helm/kind-action is broken now in general. It fails to set up the network.

~~~
Run helm/kind-action@v1.1.0
Installing kind...
Adding kind directory to PATH...
Installing kubectl...
Adding kubectl directory to PATH...
kind v0.9.0 go1.15.2 linux/amd64
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Creating kind cluster...
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.19.1) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
 • Waiting ≤ 5m0s for control-plane = Ready ⏳  ...
 ✗ Waiting ≤ 5m0s for control-plane = Ready ⏳
 • WARNING: Timed out waiting for Ready ⚠️
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂

~~~

Also see: https://github.com/ctron/kind-reproducer/runs/2951832350?check_suite_focus=true

Note: The fact that job is finished completed seems to be another issue with this action: see #41

**Comment by lukehinds** [comment] 2021-06-30 12:52
interesting , I have been banging my head the past few hours with the exact same issue:

https://github.com/sigstore/fulcio/pull/115/checks?check_run_id=2952287344#step:5:28

**Comment by cpanato** [comment] 2021-06-30 13:02
I'm going to try to reproduce the issue

**Comment by chgl** [comment] 2021-06-30 13:44
Just tried using container-tools/kind-action@v1 with the same result. So I assume it's most likely a GitHub Actions issue.

**Comment by cpanato** [comment] 2021-06-30 13:44
manage to reproduce using the current action release: https://github.com/cpanato/testing-ci-providers/runs/2952724834?check_suite_focus=true

however if I update the kind to be the latest one `v0.11.1` it works: https://github.com/cpanato/testing-ci-providers/runs/2952837429?check_suite_focus=true

**Comment by cpanato** [comment] 2021-06-30 13:45
made a PR to update the kind for the action: https://github.com/helm/kind-action/pull/43

and asap we merge that I will make a new release

**Comment by cpanato** [comment] 2021-06-30 13:45
yes, I would say as well, looks like some infrastructure change or have some issues in the gitHub side

**Comment by ctron** [comment] 2021-06-30 14:24
I can confirm, selecting v0.11.1 as kind version works.

**Comment by cpanato** [comment] 2021-06-30 14:25
@ctron just made a new release of the action to defaults kind to v0.11.1

https://github.com/helm/kind-action/releases/tag/v1.2.0


will close this issue

**Closed by cpanato** 2021-06-30 14:25 UTC

**Comment by gnarea** [comment] 2021-07-05 14:20
Thank you so much to those who worked on this!

The cause for this doesn't seem clear from looking at this issue. Is this likely to happen again? Is there anything we can do in user-land to avoid it or at least make it explicit next time it happens? I would've never thought of checking this action, since it was being marked as successful -- the failure was just marked as a warning.
